sudo: required
dist: trusty

language: python
virtualenv:
  system_site_packages: true

python:
  - "2.7"
  - "3.4"

# Use keywords to split the tests into smaller groups and therefore decrease
# the time CI takes to run.
env:
  - TESTSUITEFLAGS="-k offline -j3"
  - TESTSUITEFLAGS="-k nftables -j3"
  - TESTSUITEFLAGS="-k iptables -j3"
  - TESTSUITEFLAGS="-k iptables -j3"
    IP6TABLES="/bin/false" IP6TABLES_RESTORE="/bin/false"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y autoconf automake pkg-config intltool
    libglib2.0-dev xsltproc docbook-xsl docbook-xml iptables ipset ebtables
    libxml2-utils realpath python-dbus python3-dbus python-gi python3-gi

install:
  - pip install flake8 decorator
    && pushd /tmp
    && tar xf ${OLDPWD}/.travis/python-slip-0.6.5.tar.bz2
    && cd python-slip-0.6.5
    && make
    && sudo env PATH="$PATH" make install
    && popd
  - echo "/usr/local/lib" | sudo tee /etc/ld.so.conf.d/local.conf
  - sudo apt-get -qq -y install libmnl-dev libgmp-dev libreadline-dev
    && pushd /tmp
    && wget https://netfilter.org/projects/libnftnl/files/libnftnl-1.1.3.tar.bz2
    && wget https://netfilter.org/projects/nftables/files/nftables-0.9.1.tar.bz2
    && tar xf libnftnl-1.1.3.tar.bz2
    && tar xf nftables-0.9.1.tar.bz2
    && cd libnftnl-1.1.3
    && ./configure
    && make
    && sudo make install
    && sudo ldconfig
    && cd /tmp
    && cd nftables-0.9.1
    && ./configure --disable-man-doc
    && make
    && sudo make install
    && popd
    && sudo ldconfig

script:
  - ./autogen.sh
    && ./configure --with-ebtables-restore=/bin/false --sysconfdir=/etc
    && make -j32
  # Note: TESTSUITEFLAGS implicit from env above
  - sudo env PATH="$PATH" make check ||
    sudo env PATH="$PATH" make check TESTSUITEFLAGS="--recheck --errexit -v -d"
