blank_issues_enabled: true
contact_links:
  - name: firewalld usage mailing list
    url: https://lists.fedorahosted.org/archives/list/firewalld-users@lists.fedorahosted.org/
    about: For questions and answers regarding the usage of firewalld. Issues should be submitted via the issue tracker.
  - name: firewalld development mailing list
    url: https://lists.fedorahosted.org/archives/list/firewalld-devel@lists.fedorahosted.org/
    about: For development discussion of firewalld. Issues should be submitted via the issue tracker.
