name: testsuite
on: [push, pull_request]

jobs:
  test:
    env:
      apt-dependencies: |
        autoconf automake ebtables intltool ipset iptables libdbus-1-dev \
        libgirepository1.0-dev libglib2.0-dev libxml2-utils network-manager \
        pkg-config 
      pip-dependencies: |
        decorator dbus-python PyGObject six

    name: >-
      python-${{ matrix.python-version }}
      nftables-${{ matrix.nftables-version }}
      keyword=${{ matrix.keyword }}
      no-iptables=${{ matrix.no-iptables }}
      no-ip6tables=${{ matrix.no-ip6tables }}

    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
        libnftnl-version: [libnftnl-1.1.6]
        nftables-version: [v0.9.4]
        keyword: [offline, nftables, iptables]
        no-iptables: [false]
        no-ip6tables: [true, false]
        exclude:
          - keyword: offline
            no-ip6tables: true
          - keyword: offline
            no-iptables: true
          - keyword: iptables
            no-iptables: true
          - keyword: nftables
            no-iptables: true
            no-ip6tables: true
        include:
          - python-version: 3.7
            libnftnl-version: master
            nftables-version: master
            keyword: nftables
            no-iptables: false
            no-ip6tables: false

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: apt update
        run: sudo apt update

      - name: apt install dependencies
        run: sudo apt install -y ${{ env.apt-dependencies }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: pip install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ${{ env.pip-dependencies }}

      - name: install python-slip-dbus
        run: |
          cd /tmp
          wget --retry-connrefused https://github.com/nphilipp/python-slip/releases/download/python-slip-0.6.5/python-slip-0.6.5.tar.bz2
          tar xf python-slip-0.6.5.tar.bz2
          cd python-slip-0.6.5
          make
          python ./setup.py install

      - name: install nftables build dependencies
        run: |
          sudo apt install -y libmnl-dev libgmp-dev libreadline-dev libjansson-dev 

      - name: install libnftnl ${{ matrix.libnftnl-version }}
        run: |
          cd /tmp
          git clone --depth=1 --branch ${{ matrix.libnftnl-version }} git://git.netfilter.org/libnftnl
          cd libnftnl
          ./autogen.sh
          ./configure
          make
          sudo make install
          sudo ldconfig

      - name: install nftables ${{ matrix.nftables-version }}
        run: |
          cd /tmp
          git clone --depth=1 --branch ${{ matrix.nftables-version }} git://git.netfilter.org/nftables
          cd nftables
          ./autogen.sh
          ./configure --disable-man-doc --with-json --enable-python
          make
          sudo make install
          cd py
          pip install .
          sudo ldconfig

      - name: remove iptables, et al.
        if: ${{ matrix.no-iptables }}
        run: |
          sudo apt-get -y remove iptables ebtables ipset

      - name: build firewalld (no ip6tables)
        if: ${{ matrix.no-ip6tables }}
        run: |
          ./autogen.sh
          ./configure --disable-docs IP6TABLES=/bin/false IP6TABLES_RESTORE=/bin/false
          make -j $(nproc)

      - name: build firewalld
        if: ${{ ! matrix.no-ip6tables }}
        run: |
          ./autogen.sh
          ./configure --disable-docs
          make -j $(nproc)

      - name: run testsuite
        run: |
          sudo make -C src/tests check-local TESTSUITEFLAGS="-k ${{ matrix.keyword }} -j$(nproc)" \
          || sudo make -C src/tests check-local TESTSUITEFLAGS="--recheck --errexit --verbose"
